import React from 'react';
import { View, Text, TouchableOpacity, Animated, StyleSheet } from 'react-native';
import { Image as ExpoImage } from 'expo-image';

const ImageMessage = ({ message, scale, handleLongPress, handlePressIn, handlePressOut }) => {
  const srcMatch = message.content.match(/src="([^"]+)"/);
  
  if (!srcMatch || !srcMatch[1]) return null;

  return (
    <TouchableOpacity
      onLongPress={() => handleLongPress(message)}
      onPressIn={() => handlePressIn(scale)}
      onPressOut={() => handlePressOut(scale)}
      delayLongPress={200}
      activeOpacity={1}
    >
      <Animated.View 
        style={[
          styles.imageContainer,
          { 
            alignSelf: message.role === 'user' ? 'flex-end' : 'flex-start',
            transform: [{ scale }]
          }
        ]}
      >
        <ExpoImage
          source={{ uri: srcMatch[1] }}
          style={styles.messageImage}
          contentFit="cover"
          transition={200}
        />
        <Text style={styles.imageCaption}>Generated by DALL-E 3</Text>
      </Animated.View>
    </TouchableOpacity>
  );
};

const styles = StyleSheet.create({
  imageContainer: {
    width: '75%',
    marginBottom: 10,
  },
  messageImage: {
    width: '100%',
    height: 300,
    borderRadius: 18,
  },
  imageCaption: {
    fontSize: 10,
    color: '#8E8E93',
    textAlign: 'left',
    marginLeft: 10,
    marginTop: 4,
    marginBottom: 10,
  },
});

export default ImageMessage;
