import React, { useEffect, useState } from 'react';
import { View, Text, TouchableOpacity, StyleSheet, ScrollView, Modal } from 'react-native';
import { Image as ExpoImage } from 'expo-image';
import Animated, { 
  useAnimatedStyle, 
  withTiming, 
  withSpring,
  interpolate,
  useSharedValue,
  runOnJS
} from 'react-native-reanimated';

const ImageMessage = ({ 
  message, 
  handleLongPress, 
  isFlipped,
  onFlipEnd,
  onFlip,
  messages
}) => {
  const scale = useSharedValue(1);
  const flipAnimation = useSharedValue(0);
  const srcMatch = message.content.match(/src="([^"]+)"/);
  const revisedPromptMatch = message.content.match(/data-revised-prompt="([^"]+)"/);
  const revisedPrompt = revisedPromptMatch ? revisedPromptMatch[1] : null;
  
  const handlePressIn = () => {
    scale.value = withSpring(0.98);
  };

  const handlePressOut = () => {
    scale.value = withSpring(1);
  };

  const handleFlipBack = () => {
    flipAnimation.value = withTiming(0, { duration: 500 }, (finished) => {
      if (finished) {
        runOnJS(onFlipEnd)();
      }
    });
  };
  
  useEffect(() => {
    if (isFlipped) {
      flipAnimation.value = withTiming(1, { duration: 500 });
    }
  }, [isFlipped]);

  const [isFullScreen, setIsFullScreen] = useState(false);

  const handlePress = () => {
    setIsFullScreen(true);
  };

  const handleCloseFullScreen = () => {
    setIsFullScreen(false);
  };

  const FullScreenImage = () => (
    <Modal
      visible={isFullScreen}
      transparent={true}
      onRequestClose={handleCloseFullScreen}
    >
      <TouchableOpacity 
        style={styles.fullScreenContainer} 
        activeOpacity={1} 
        onPress={handleCloseFullScreen}
      >
        <ExpoImage
          source={{ uri: srcMatch[1] }}
          style={styles.fullScreenImage}
          contentFit="contain"
          transition={200}
        />
        <TouchableOpacity 
          style={styles.closeFullScreenButton}
          onPress={handleCloseFullScreen}
        >
          <Text style={styles.closeFullScreenText}>×</Text>
        </TouchableOpacity>
      </TouchableOpacity>
    </Modal>
  );

  if (!srcMatch || !srcMatch[1]) return null;

  const frontAnimatedStyle = useAnimatedStyle(() => {
    const rotateY = interpolate(
      flipAnimation.value,
      [0, 1],
      [0, -180]
    );
    return {
      transform: [
        { perspective: 1000 },
        { rotateY: `${rotateY}deg` },
        { scale: scale.value }
      ],
      backfaceVisibility: 'hidden',
    };
  });

  const backAnimatedStyle = useAnimatedStyle(() => {
    const rotateY = interpolate(
      flipAnimation.value,
      [0, 1],
      [-180, -360]
    );
    return {
      transform: [
        { perspective: 1000 },
        { rotateY: `${rotateY}deg` },
        { scale: scale.value }
      ],
      backfaceVisibility: 'hidden',
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
    };
  });

  return (
    <TouchableOpacity
      onPress={handlePress}
      onLongPress={() => handleLongPress(message, isFlipped)}
      onPressIn={() => handlePressIn()}
      onPressOut={() => handlePressOut()}
      delayLongPress={200}
      activeOpacity={1}
    >
      <View style={[
        styles.imageContainer,
        { alignSelf: message.role === 'user' ? 'flex-end' : 'flex-start' }
      ]}>
        <Animated.View style={frontAnimatedStyle}>
          <ExpoImage
            source={{ uri: srcMatch[1] }}
            style={styles.messageImage}
            contentFit="cover"
            transition={200}
          />
          <Text style={styles.imageCaption}>Generated by DALL-E 3</Text>
        </Animated.View>

        <Animated.View style={[styles.backContainer, backAnimatedStyle]}>
          <View style={styles.infoContent}>
            <TouchableOpacity 
              onPress={handleFlipBack}
              style={styles.closeButton}
            >
              <Text style={styles.closeButtonText}>×</Text>
            </TouchableOpacity>
            {revisedPrompt && (
              <View style={styles.promptOuterContainer}>
                <Text style={styles.promptLabel}>DALL-E's Interpretation:</Text>
                <ScrollView 
                  style={styles.promptScrollContainer}
                  contentContainerStyle={styles.promptContentContainer}
                  showsVerticalScrollIndicator={true}
                >
                  <Text style={styles.promptText}>{revisedPrompt}</Text>
                </ScrollView>
              </View>
            )}
          </View>
        </Animated.View>
      </View>
      <FullScreenImage />
    </TouchableOpacity>
  );
};

const styles = StyleSheet.create({
  imageContainer: {
    width: '75%',
    marginBottom: 10,
  },
  messageImage: {
    width: '100%',
    height: 300,
    borderRadius: 18,
  },
  captionContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 10,
    marginTop: 4,
    marginBottom: 10,
  },
  imageCaption: {
    fontSize: 10,
    color: '#8E8E93',
  },
  moreInfo: {
    fontSize: 10,
    color: '#007AFF',
  },
  backContainer: {
    width: '100%',
    height: 300,
    backgroundColor: '#F2F2F7',
    borderRadius: 18,
  },
  infoContent: {
    flex: 1,
    padding: 20,
    paddingTop: 0,
  },
  infoTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 20,
    color: '#1C1C1E',
  },
  infoText: {
    fontSize: 14,
    color: '#3A3A3C',
    marginBottom: 10,
  },
  flipBackButton: {
    marginTop: 20,
    padding: 10,
    backgroundColor: '#007AFF',
    borderRadius: 8,
  },
  flipBackText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  closeButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#007AFF',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  closeButtonText: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: 'bold',
  },
  promptOuterContainer: {
    flex: 1,
    marginTop: 20,
    marginBottom: 10,
  },
  promptLabel: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#1C1C1E',
    marginBottom: 8,
  },
  promptScrollContainer: {
    flex: 1,
    // backgroundColor: 'rgba(0,0,0,0.05)',
    // borderRadius: 10,
  },
  promptContentContainer: {
    // padding: 15,
  },
  promptText: {
    fontSize: 14,
    color: '#3A3A3C',
    lineHeight: 20,
  },
  fullScreenContainer: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fullScreenImage: {
    width: '100%',
    height: '100%',
  },
  closeFullScreenButton: {
    position: 'absolute',
    top: 40,
    right: 20,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeFullScreenText: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: 'bold',
  },
});

export default ImageMessage;
